name: CMake

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3

  - name: Adding gtest
    run: git clone https://github.com/google/googletest.git third-party/gtest -b release-1.11.0

  - name: Install lcov
    run: sudo apt-get install -y lcov

  - name: Config banking with tests
    run: cmake -H. -B ${{github.workspace}}/build -DBUILD_TESTS=ON

  - name: Build banking
    run: cmake --build ${{github.workspace}}/build

  - name: Run tests
    run: build/check
    
  - name: Do lcov stuff
    run: lcov --directory . --capture --output-file coverage.info
    
  - name: lcov stuff2
    run: lcov --remove coverage.info '/usr/*' --output-file coverage.info
    
  - name: lcov stuff3
    run: lcov --remove coverage.info '${{github.workspace}}/third-party/gtest/*' --output-file coverage.info
    
  - name: lcov stuff4
    run: lcov --list coverage.info

  - name: Coveralls
    uses: coverallsapp/github-action@master
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      path-to-lcov: ${{ github.workspace }}/coverage.info
  
  
  
  
  
  
  
  
  
  
  
  
